### ISSUE TITLE
컴포넌트 분리 등 코드 리팩토링

### ISSUE THREAD

**Issue by jsh3418** [kiosk-team-7/kiosk-max#66]
## 만들고자 하는 기능이 무엇인가요?
컴포넌트 분리 등 코드 리팩토링

## 해당 기능을 구현하기 위해 할 일이 무엇인가요?
- [x] 1. 컴포넌트 코드, 파일 분리
- [x] 2. 버그 수정

**Comment by n-aa-g** [comment]
LGTM
